name: scp files
on:
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 4.240.76.246
        username: vThink_cloud_server
        password: vTk2024hyen@
        port: 22
        source: "./build/index.nginx-debian.html"
        target: /etc/demo
        timeout: 5m
