name: Deploy to Ubuntu Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Files in the Repository
        run: |
          echo "Listing files in the repository"
          ls -alh

      - name: Find and Rename the Build File
        run: |
          echo "Renaming the build file"
          mv ./build/* ./build/index.nginx-debian.html

      - name: Copy Build File to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: ./build/index.nginx-debian.html
          target: /var/www/html
          timeout: 10m
          debug: true

      - name: Restart Nginx
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: sudo systemctl restart nginx

      - name: Clean Up Private Key
        if: always()
        run: rm -f private_key
