name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 777 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install -y sshpass

      - name: Test SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.ARTIFACT_USER }}@${{ secrets.ARTIFACT_HOST }} echo "SSH connection successful"

      - name: List Files in the Repository
        run: ls -alh

      - name: Add SSH key to ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Copy Build File to Server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: '${{ secrets.ARTIFACT_HOST }}'
          username: '${{ secrets.ARTIFACT_USER }}'
          key: '${{ secrets.ARTIFACT_SSH_KEY }}'
          source: ./build/index.nginx-debian.html
          target: /var/www/html
          timeout: 10m
          debug: true

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: '${{ secrets.ARTIFACT_HOST }}'
          username: '${{ secrets.ARTIFACT_USER }}'
          key: '${{ secrets.ARTIFACT_SSH_KEY }}'
          script: sudo systemctl restart nginx
