name: Deploy to Ubuntu Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: List Files in the Repository
      run: |
        echo "Listing files in the repository"
        ls -alh
    - name: Find and Rename the Build File
      run: |
        echo "Renaming the build file"
        # Assuming the build file is inside a folder like 'build/' in your repository
        mv ./build/* ./build/index.nginx-debian.html
    - name: Copy Build File to Server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./build/index.nginx-debian.html
        target: /var/www/html

    - name: Restart Nginx
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx
